# Generated by Django 3.0.2 on 2020-01-30 16:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.CharField(max_length=256, verbose_name='License Number')),
                ('driver_status', models.CharField(default='No', max_length=256)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible')], default='Sedan', max_length=256, verbose_name='Vehicle Type')),
                ('vehicle_make', models.CharField(default='', max_length=256, verbose_name='Make')),
                ('plate_number', models.CharField(default='', max_length=256, verbose_name='Plate Number')),
                ('vehicle_capacity', models.IntegerField(default=4, verbose_name='Capacity')),
                ('special_vehicle_info', models.TextField(default='', verbose_name='Special Vehicle Info')),
            ],
        ),
        migrations.CreateModel(
            name='Sharer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_arr', models.CharField(default='', max_length=256)),
                ('earliest_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Earliest Time')),
                ('latest_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Latest Time')),
                ('no_persons_sharer', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Passengers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sharer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('dest_addr', models.CharField(default='', max_length=512, verbose_name='Your Destination')),
                ('arr_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Arrival Time')),
                ('no_persons_owner', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Passengers')),
                ('owner_vehicle_type', models.CharField(choices=[('All', 'All'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible')], default='All', max_length=256, verbose_name='Vehicle Type')),
                ('special_request', models.TextField(blank=True, verbose_name='Special Request')),
                ('can_shared', models.BooleanField(default=False, verbose_name='Share your ride')),
                ('max_allowed_persons', models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max Sharers Allowed')),
                ('status', models.CharField(default='', max_length=256)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver', to='ride_app.Driver')),
                ('owner', models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('sharer', models.ManyToManyField(related_name='sharer', to='ride_app.Sharer')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='ride_app.Vehicle'),
        ),
    ]
