# Generated by Django 3.0.2 on 2020-01-30 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arr_date_time',
            field=models.DateTimeField(default='2020-01-30 23:09', verbose_name='Arrival Time'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='max_allowed_persons',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max Sharers Allowed'),
        ),
        migrations.AlterField(
            model_name='sharer',
            name='earliest_time',
            field=models.DateTimeField(default='2020-01-30 23:09', verbose_name='Earliest Time'),
        ),
        migrations.AlterField(
            model_name='sharer',
            name='latest_time',
            field=models.DateTimeField(default='2020-01-30 23:09', verbose_name='Latest Time'),
        ),
    ]
