# Generated by Django 3.0.2 on 2020-01-31 04:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ride_app', '0002_auto_20200130_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arr_date_time',
            field=models.DateTimeField(default='2020-01-31 04:42', verbose_name='Arrival Time'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='max_allowed_persons',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max Sharers Allowed'),
        ),
        migrations.AlterField(
            model_name='sharer',
            name='earliest_time',
            field=models.DateTimeField(default='2020-01-31 04:42', verbose_name='Earliest Time'),
        ),
        migrations.AlterField(
            model_name='sharer',
            name='latest_time',
            field=models.DateTimeField(default='2020-01-31 04:42', verbose_name='Latest Time'),
        ),
        migrations.AlterField(
            model_name='sharer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sharer', to=settings.AUTH_USER_MODEL),
        ),
    ]
