# Generated by Django 2.2.10 on 2020-02-05 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ride_app', '0003_auto_20200131_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='arr_date_time',
            field=models.DateTimeField(default='2020-02-05 22:35', verbose_name='Arrival Time'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rides', to='ride_app.Driver'),
        ),
        migrations.AlterField(
            model_name='sharer',
            name='earliest_time',
            field=models.DateTimeField(default='2020-02-05 22:35', verbose_name='Earliest Time'),
        ),
        migrations.AlterField(
            model_name='sharer',
            name='latest_time',
            field=models.DateTimeField(default='2020-02-05 22:35', verbose_name='Latest Time'),
        ),
    ]
